name: CI

on:
  push: {}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Nix
      uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: experimental-features = nix-command flakes

    - name: Verify all lines are valid
      run: |
        nix run .#year-of-bot -- verify
    
    - name: Ensure data is sorted
      run: |
        ./sort-data.sh && git diff --exit-code
